# Generated by Django 5.1.2 on 2024-10-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=255)),
                ('tested', models.BooleanField(default=False)),
                ('interests', models.ManyToManyField(related_name='employees', to='phishing.interesttag')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона ')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('interests', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='phishing.interesttag')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('employees', models.ManyToManyField(related_name='phishing_tests', to='phishing.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PhishingTestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='Clicked Link', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.employee')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.phishingtest')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_email', models.BooleanField(default=False)),
                ('clicked_link', models.BooleanField(default=False)),
                ('reported_email', models.BooleanField(default=False)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.employee')),
                ('phishing_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phishing.phishingtest')),
            ],
        ),
    ]
