# Generated by Django 5.1.2 on 2024-10-21 18:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='emails_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='submitted_correct_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='submitted_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='interests',
            field=models.ManyToManyField(default=None, related_name='employees', to='phishing.interesttag'),
        ),
        migrations.AlterField(
            model_name='phishingemailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Тело письма'),
        ),
    ]
